from django.conf import settings
from django.core.checks import Warning, register


@register()
def cache_backend_check(app_configs, **kwargs):
    """LocMemCache is per-process. OTP codes and the login/verify/resend
    throttle counters live in Django's cache (see settings.py), so behind
    multi-worker Gunicorn without Redis: an OTP generated by the worker that
    handled login can be invisible to the worker that handles verify, and a
    "5/min" throttle silently becomes "5/min x worker count". DEBUG=True (or
    running with a single process, e.g. CI/local `manage.py test`) is exempt
    since neither is the deployment shape this actually breaks."""
    if not settings.DEBUG and not getattr(settings, "REDIS_URL", ""):
        return [
            Warning(
                "REDIS_URL is not set and DEBUG is False -- OTP codes and rate-limit "
                "counters will be per-process under multi-worker Gunicorn.",
                hint="Set REDIS_URL in the environment before deploying with more than one worker process.",
                id="portal.W001",
            )
        ]
    return []
