# Generated by Django 5.0.6 on 2026-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_admissionenquiry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='needs_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='preferred_pickup_point',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
