# Generated by Django 5.0.6 on 2026-07-09 16:54

import apps.admissions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_admissionenquiry_needs_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionenquiry',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.admissions.models.validate_document_size]),
        ),
    ]
